version: "2"
services:
  nginx:
    restart: always
    # build: ./nginx
    image: pyar6329/elib-docker:nginx-latest
    cpu_shares: 10
    mem_limit: 64m
    links:
      - "elib"
    ports:
     - "80:80"
    depends_on:
      - "fluentd"
    logging:
      driver: fluentd
      options:
        tag: docker.{{.Name }}
        # fluentd-address: fluentd:24224
  elib:
    restart: always
    image: pyar6329/elib:0.1.0
    cpu_shares: 10
    mem_limit: 128m
    expose:
     - "3000"
    depends_on:
      - "fluentd"
    logging:
      driver: fluentd
      options:
        tag: docker.{{.Name }}
        # fluentd-address: fluentd:24224
  redis:
    restart: always
    # build: ./redis
    image: pyar6329/elib-docker:redis-latest
    cpu_shares: 10
    mem_limit: 64m
    ports:
      - "6379:6379"
    depends_on:
      - "fluentd"
    logging:
      driver: fluentd
      options:
        tag: docker.{{.Name }}
        # fluentd-address: fluentd:24224
  elasticsearch:
    restart: always
    image: elasticsearch:2.3
    cpu_shares: 10
    mem_limit: 512m
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    depends_on:
      - "fluentd"
    logging:
      driver: fluentd
      options:
        tag: docker.{{.Name }}
        # fluentd-address: fluentd:24224
  fluentd:
    restart: always
    # build: ./fluentd
    image: pyar6329/elib-docker:fluentd-latest
    cpu_shares: 10
    mem_limit: 64m
    ports:
      - "24224:24224"
    env_file: ./fluentd/secrets.env
    # expose:
    #  - "24224"
