version: "2"
services:
  data:
    image: data:latest
    volumes:
      - ./var/postgresql/data:/var/lib/postgresql/data
      - ./repos:/root/elib

  redis:
    restart: always
    image: redis:3-alpine
    depends_on:
      - data
    volumes_from:
      - data
    command: redis-server /etc/redis/redis.conf

  elasticsearch:
    restart: always
    image: elasticsearch:2.3
    command: elasticsearch -Des.network.host=0.0.0.0

  postgresql:
    restart: always
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=elib
      - POSTGRES_USER=elib
      - POSTGRES_DB=elib
    volumes_from:
      - data

  elib:
    restart: always
    image: pyar6329/elib:0.1.0
    depends_on:
      - redis
      - postgresql
      - elasticsearch
    links:
      - redis
      - postgresql
      - elasticsearch
    expose:
      - "3000"
    environment:
      - DB_HOST=127.0.0.1
      - DB_DATABASE=elib
      - DB_USERNAME=elib
      - DB_PASSWORD=elib

  nginx:
    restart: always
    image: nginx:mainline-alpine
    depends_on:
      - data
      - elib
    volumes_from:
      - data
    links:
      - elib
    ports:
     - "80:80"
