version: "2"
services:
  data:
    image: pyar6329/rails-base:data-latest
    volumes:
      - ./var/postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:3-alpine
    volumes_from:
      - data
    command: redis-server /etc/redis/redis.conf

  elasticsearch:
    image: elasticsearch:2.4-alpine
    command: elasticsearch -Des.network.host=0.0.0.0

  postgresql:
    build: ./builds/development/postgres
    volumes_from:
      - data
    env_file:
      - ./env/psql.env
#    ports:
#      - "5432:5432"

  elib:
    build: ./builds/development/rails
    volumes_from:
      - data
    volumes:
      - ./builds/development/rails/app:/usr/src/app
    depends_on:
      - redis
      - postgresql
      - elasticsearch
    links:
      - "redis:redis"
      - "postgresql:postgresql"
      - "elasticsearch:elasticsearch"
    env_file:
      - ./env/elib.env

  nginx:
    image: nginx:mainline-alpine
    volumes_from:
      - data
    depends_on:
      - data
      - elib
    volumes_from:
      - data
    links:
      - "elib:elib"
    ports:
     - "80:80"
    entrypoint: dockerize -wait tcp://elib:3000 -timeout 300s
    command: nginx -g 'daemon off;'
