version: "2"
services:
  data:
    image: pyar6329/rails-base:data-latest
    volumes:
      - ./var/postgresql/data:/var/lib/postgresql/data
    networks:
      web_server:
        aliases:
          - data

  redis:
    image: redis:3-alpine
    volumes_from:
      - data
    command: redis-server /etc/redis/redis.conf
    networks:
      web_server:
        aliases:
          - redis

  elasticsearch:
    image: elasticsearch:2.3
    command: elasticsearch -Des.network.host=0.0.0.0
    networks:
      web_server:
        aliases:
          - elasticsearch

  postgresql:
    build: ./builds/development/postgres
    volumes_from:
      - data
    env_file:
      - ./env/psql.env
    networks:
      web_server:
        aliases:
          - postgresql

  elib:
    build: ./builds/development/rails
    volumes_from:
      - data
    volumes:
      - ./builds/development/rails/app:/usr/src/app
    depends_on:
      - redis
      - postgresql
      - elasticsearch
    links:
      - "redis:redis"
      - "postgresql:postgresql"
      - "elasticsearch:elasticsearch"
    env_file:
      - ./env/elib.env
    networks:
      web_server:
        ipv4_address: 172.25.0.21
        aliases:
          - elib
networks:
  web_server:
    external: true

